### ISSUE TITLE
AVS

### ISSUE THREAD

**Issue by johnwheeler** [caiismyname/Alexa-on-Pi#1]
Hi David,

Did you ever get this going? 

http://stackoverflow.com/questions/38019382/avs-v2-establishing-http2-connection

**Comment by caiismyname** [comment]
Hi John,

Sorry for the late response. I shelved that project for the time being. I don't know enough about the topic to be a forerunner in it haha. Sorry!

**Comment by johnwheeler** [comment]
I got something going for it! I'll post some code soon
